

text_1 = """We can't imagine our life without books. They play a very important part in our life. Books are our friends. We meet them when we are very small and can't read, but we remember our mother read them for us. We learn very much from books. Books educate people in different spheres of life. They develop our imagination, make us think and analyse. They help to form our character and the world outlook. Books help us in self education and in deciding problems of life. They make our life more interesting. People read both for knowledge and for pleasure. Different people read different books. They help us with our lessons and work. We read serious books which help us understand the life, give us answers to questions which worry us, they make us think. Many people enjoy so-called "easy reading" - detectives, amusing, humorous stories, fantastic. But so many people, so many tastes. As for me, I prefer to read adventure stories, full of interesting real fact and pictures, and detectives. My favourite author is Arthur Conan Doyle with his Holmes' adventures."""


text_2 = """The United Kingdom of Great Britain and Northern Ireland with an area of 244 000 square miles is situated on the British Isles, which are separated from the European continent by the North Sea, the Strait of Dover and the English Channel. Britain's population is over 56 million. Four out of five people live in towns. The largest cities of the country are London, Birmingham, Liverpool, Manchester, Glasgow and Edinburgh. The UK is a monarchy: the head of the state is a king or a queen. In practice, the Sovereign reigns, but does not rule: the UK is governed by the Government. The present Sovereign is Queen Elizabeth II. The territory of Great Britain is small. Yet the country has a wide variety of scenery. The heart of Britain is England. It is the richest, the most fertile and most populated in the country. The north and the west of England are mountainous, but all the rest of territory is a vast plain. In Northwest England, there are many beautiful lakes with green, wooded or grassy shores and grey mountains all around. The smallest of Britain's countries is Wales. The largest part of Wales is covered with rocky mountains, which are difficult to climb. Most people in Wales live in the coastal plains. Scotland is a land of mountains, wild moorlands, narrow valleys and plains, famous lakes and no end of large and small islands. The Highlands of Scotland are among the oldest mountains in the world. One-third of the people in Scotland live in or near its capital, Edinburgh, and its great industrial center, Glasgow. The capital of Great Britain, London, stands on the Thames. The Thames is the busiest and the most important river in Great Britain, but it is not very long. The climate of Great Britain is mild."""


text_3 = """To be, or not to be - that is the question: Whether 'tis nobler in the mind to suffer The slings and arrows of outrageous fortune, Or to take arms against a sea of troubles, And by opposing end them. To die, to sleep - No more, and by a sleep to say we end The heartache, and the thousand natural shocks That flesh is heir to; 'tis a consummation Devoutly to be wished. To die, to sleep - To sleep - perchance to dream... Ay, there's the rub, For in that sleep of death what dreams may come, When we have shuffled off this mortal coil Must give us pause. There's the respect That makes calamity of so long life."""


text_4 = """A great number of items in collections of books, newspapers, periodicals, manuscripts, films, maps and works of drama, music, art and important and exciting documents from American history are kept in library's archives. There are materials on practically every subject to which members of Congress can refer. And now I would tell you about Lenin State Library. The Lenin Library is the central library and is one of the world's largest. The old library building was built in 1786 on a hill opposite the Kremlin by Vasily Bashenov and was a typical example of a Moscow town residence of that time. Its new buildings were built in 1940. 
            When the library was founded in 1961, it contained over 1000.000 volumes, and was then located in the old Pashkov part of the complex. In 1915 its one reading room had a sitting capacity of only 170. 
            Now it has 23 reading rooms of 2500 seating capacities and a book fund of 27 millions. 
            There a wide choice of books: fiction, non-fiction, serious books, detective stories, science fiction, biographic, history and encyclopedias which are extremely useful in work, because it gives information about every branch of knowledge. Of cource there is a catalogue of books. """ 


text_5 = """Ключ - секретная информация, используемая криптографическим алгоритмом при зашифровании / расшифровании сообщений, постановке и проверке цифровой подписи, вычислении кодов аутентичности. При использовании одного и того же алгоритма результат шифрования зависит от ключа."""